version: '3.1'

services:

  web:
    image: demo-website
    build: web
    environment:
      MYSQL_USERNAME: "${MYSQL_USERNAME}"
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
    ports:
      - "5000:5000"

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    volumes:
    - flyway-demo-data:/var/lib/mysql
    ports:
    - "3306:3306"

  flyway:
    image: flyway/flyway:6.1.0-alpine
    # Migrate
    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password="${MYSQL_ROOT_PASSWORD}" -connectRetries=60 migrate
    # Repair
#    command: -url=jdbc:mysql://db -schemas=myschema -user=root -password="${MYSQL_ROOT_PASSWORD}" -connectRetries=60 repair
    volumes:
    - "./db/sql:/flyway/sql"
    depends_on:
      - db

volumes:
  flyway-demo-data: